name: pp_19
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  in_app_review: ^2.0.8
  url_launcher: ^6.2.4

  #injections
  get_it: ^7.6.4

  #data base
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #provider
  path_provider: ^2.1.2

  #date-formatting
  intl: ^0.17.0

  #statistic view
  fl_chart: ^0.66.0

  webview_flutter_wkwebview: ^3.10.2
  webview_flutter_android: ^3.14.0
  webview_flutter: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  firebase_core: ^2.25.2
  firebase_crashlytics: ^3.4.12
  firebase_remote_config: ^4.3.11
  flutter_app_info: ^2.0.0
  connectivity_plus: ^5.0.2
  flutter_markdown: ^0.6.18+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon_rounded.png


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
